### PR TITLE
installer.sh and readme.md updated

### PR DESCRIPTION
**Pull request by AliAsghar01**
Signed-off-by: Ali Asghar <alan.asgharawan@gmail.com>

### CODE REVIEW

**Comment by FendVario1** [comment]
1. why is Python still a requirement in readme?
Also please check the following errors:
image

**Comment by tariqmagsi** [comment]
it will run on using bash.
sudo bash ./installer.sh

**Comment by tariqmagsi** [comment]
> 1. why is Python still a requirement in readme?
>    Also please check the following errors:
>    image
it will run on using bash.
sudo bash ./installer.sh

**Comment by FendVario1** [comment]
Sorry my fault. However, the missing dependencies issue still persists:
image

Also please make the readme more readable using newlines for the running steps.

**Comment by tariqmagsi** [comment]
> Sorry my fault. However, the missing dependencies issue still persists: image
> 
> Also please make the readme more readable using newlines for the running steps.

its updated now

**Pull request merged**
